-- Advisor Corpus (How to Invest My Money project): channels, videos, claims.
-- Mirror pattern like spend_*: the Mac-local corpus pipeline pushes rows;
-- the dashboard only reads (/api/invest). Seeds are generated by
-- scripts/build-invest-seed.mjs from the pipeline's TestRuns output.

CREATE TABLE IF NOT EXISTS invest_channels (
  id TEXT PRIMARY KEY,                -- handle without @, e.g. 'BenFelixCSI'
  name TEXT NOT NULL,
  handle TEXT NOT NULL,
  style TEXT,                         -- e.g. 'Evidence-based', 'Macro narrative'
  jurisdiction TEXT,                  -- global | US | EU | NL
  on_roster INTEGER NOT NULL DEFAULT 0,
  notes TEXT,
  synced_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS invest_videos (
  id TEXT PRIMARY KEY,                -- YouTube video id
  channel_id TEXT NOT NULL REFERENCES invest_channels(id),
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  views INTEGER,
  duration_s INTEGER,
  upload_date TEXT,
  words INTEGER,
  transcript_source TEXT,             -- auto | manual | whisper
  summary_md TEXT,
  claims_total INTEGER NOT NULL DEFAULT 0,
  claims_validated INTEGER NOT NULL DEFAULT 0,
  claims_quarantined INTEGER NOT NULL DEFAULT 0,
  processed_at TEXT,
  synced_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS invest_claims (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  video_id TEXT NOT NULL REFERENCES invest_videos(id),
  claim TEXT NOT NULL,
  type TEXT NOT NULL,                 -- fact|recommendation|prediction|opinion|numeric|warning
  stance TEXT NOT NULL,               -- asserts|reports_other|hypothetical
  quote TEXT,
  jurisdiction TEXT,                  -- global | US | EU | NL
  validated INTEGER NOT NULL DEFAULT 0,
  synced_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_invest_videos_channel ON invest_videos(channel_id);
CREATE INDEX IF NOT EXISTS idx_invest_claims_video ON invest_claims(video_id);
