INSERT OR IGNORE INTO move_tasks (id, bucket, seq, title, owner, due, status, notes) VALUES
  ('A1', 'A', 1, 'Confirm exact eindinspectie / key-handover date with Inter Immo / Ravi', 'Y', NULL, 'todo', '**Do first** — everything else dates off this'),
  ('A2', 'A', 2, 'Find original opname/intake report + intake photos to compare condition', 'YN', NULL, 'todo', 'Defines what "original state" means'),
  ('A3', 'A', 3, 'Pre-inspection walkthrough room-by-room vs the intake report', 'YN', NULL, 'todo', NULL),
  ('A4', 'A', 4, 'Fill/sand nail + drill holes; touch-up or repaint walls to original', 'YN', NULL, 'todo', NULL),
  ('A5', 'A', 5, 'Wallpaper (טפטים): check cost + what''s needed for it', 'YN', NULL, 'todo', 'Get a quote; decide DIY vs hire'),
  ('A6', 'A', 6, 'Re-hang the door + the top frame/lintel', 'Y', NULL, 'todo', 'Restore to original'),
  ('A7', 'A', 7, 'Reassemble table + cabinets back in the living room', 'Y', NULL, 'todo', 'Return furniture to original layout'),
  ('A8', 'A', 8, 'Move bed down from 3rd floor to 2nd floor', 'Y', NULL, 'todo', NULL),
  ('A9', 'A', 9, 'Tidy the yard / garden to agreed state', 'YN', NULL, 'todo', NULL),
  ('A10', 'A', 10, 'Clean mold — washing machine + shower room', 'YN', NULL, 'todo', NULL),
  ('A11', 'A', 11, 'Ask Ravi if he wants to arrange a deep kitchen cleaning', 'Y', NULL, 'todo', 'Landlord may prefer to organize it himself'),
  ('A12', 'A', 12, 'Remove all self-installed fixtures (shelves, lamps) unless taken over', 'YN', NULL, 'todo', NULL),
  ('A13', 'A', 13, 'Final meter readings (electricity, gas, water) + dated photos', 'Y', NULL, 'todo', NULL),
  ('A14', 'A', 14, 'Count + hand over all keys, remotes, fobs', 'Y', NULL, 'todo', NULL),
  ('A15', 'A', 15, 'Agree waarborgsom (deposit) return amount + timeline in writing', 'Y', NULL, 'todo', NULL),
  ('A16', 'A', 16, 'Get written "akkoord oplevering" + deposit settlement', 'Y', NULL, 'todo', 'Close-out proof'),
  ('B1', 'B', 1, '⚠️ Ziggo internet — runs to **28 Nov 2026**, move is summer → terminate / transfer / overlap', 'Y', NULL, 'todo', 'Call Ziggo; ask about verhuisregeling vs early-termination cost'),
  ('B2', 'B', 2, 'Energy — verhuizing doorgeven; final reading old, start new', 'Y', NULL, 'todo', NULL),
  ('B3', 'B', 3, 'Water company — register the move', 'Y', NULL, 'todo', NULL),
  ('B4', 'B', 4, 'Gemeente — deregister Leiderdorp + register new municipality (BRP)', 'Y', NULL, 'todo', 'Within legal window around move date'),
  ('B5', 'B', 5, 'PostNL verhuisservice — mail forwarding', 'Y', NULL, 'todo', NULL),
  ('B6', 'B', 6, 'Update address: banks, insurers, DigiD-linked, KvK (Yaron Kra IT), SVB/pension, subscriptions', 'Y', NULL, 'todo', NULL),
  ('B7', 'B', 7, 'Home/contents insurance (inboedel) — update for new address', 'Y', NULL, 'todo', NULL),
  ('B8', 'B', 8, '4× schools — notify leaving date + confirm placement/start at new schools', 'YN', NULL, 'todo', 'Ties to NL Schools work'),
  ('B9', 'B', 9, 'Huisarts (GP) + dentist — re-register near new place', 'YN', NULL, 'todo', NULL),
  ('B10', 'B', 10, 'Car/RDW + MRB address (Tesla TJ-837-T) if still owned at move', 'Y', NULL, 'todo', NULL),
  ('C1', 'C', 1, 'Buy 2× freezer drawers (מגירות פריזר)', 'YN', NULL, 'todo', 'Confirm model/size that fits'),
  ('C2', 'C', 2, 'Internet install at new address — order early', 'Y', NULL, 'todo', 'Install lead time can be weeks'),
  ('C3', 'C', 3, 'Energy contract at new address', 'Y', NULL, 'todo', NULL),
  ('C4', 'C', 4, 'Measure all rooms; floorplan + furniture placement', 'YN', NULL, 'todo', NULL),
  ('C5', 'C', 5, 'Buy-list: appliances, furniture, 4 kids'' rooms, curtains/blinds, lighting', 'YN', NULL, 'todo', NULL),
  ('C6', 'C', 6, 'Organize the closet/cabinet in Ori & Yuvi''s room', 'YN', NULL, 'todo', NULL),
  ('D1', 'D', 1, 'Order a roll of bubble wrap (פצפוצים) for wrapping', 'Y', NULL, 'todo', NULL),
  ('D2', 'D', 2, 'Buy moving boxes / cartons', 'Y', NULL, 'todo', NULL),
  ('D3', 'D', 3, 'Pack winter clothes + coats', 'YN', NULL, 'todo', 'Off-season → pack early'),
  ('D4', 'D', 4, 'Pack books + toys', 'YN', NULL, 'todo', NULL),
  ('D5', 'D', 5, 'Throw out unneeded scooters (קורקינטים)', 'YN', NULL, 'todo', NULL),
  ('D6', 'D', 6, 'Pin the 3 key dates: new-key handover / moving day / Kloosterhof oplevering', 'YN', NULL, 'todo', NULL),
  ('D7', 'D', 7, 'Book moving company OR rent van + arrange helpers', 'Y', NULL, 'todo', NULL),
  ('D8', 'D', 8, 'Childcare / time off for moving days (4 boys)', 'YN', NULL, 'todo', NULL),
  ('D9', 'D', 9, 'Declutter / sell / donate before packing (Marktplaats)', 'YN', NULL, 'todo', NULL);
